version: 2.1

jobs:
  sonar:
    docker:
      - image: circleci/node:14.17-browsers # Use a Node image with browser support if needed for frontend testing
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install # Adjust this to fit your project's package manager (e.g., yarn install)
      - run:
          name: Run SonarQube Analysis
          command: |
            npm install -g sonar-scanner
            sonar-scanner \
              -Dsonar.projectKey=caroline-amy_SecurePaymentPortal \
              -Dsonar.organization=caroline-amy \
              -Dsonar.sources=. \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  sonar_workflow:
    jobs:
      - sonar
